# Generated by Django 4.2.9 on 2024-04-24 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('category_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookCode',
            fields=[
                ('code_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('code_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100, null=True)),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('publisher_date', models.DateField(max_length=40, null=True)),
                ('summary', models.CharField(max_length=1000, null=True)),
                ('price', models.IntegerField(null=True)),
                ('keeper_id', models.IntegerField(null=True)),
                ('category', models.ForeignKey(max_length=8, on_delete=django.db.models.deletion.CASCADE, to='books.bookcategory')),
                ('status', models.ForeignKey(max_length=24, on_delete=django.db.models.deletion.CASCADE, to='books.bookcode')),
            ],
        ),
        migrations.CreateModel(
            name='BookLendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookdata')),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
